//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Point : MonoBehaviour
{
	public Vector2 prevPos;
	public Vector2 currPos;
	public Vector2 acceleration;
	public int id = 0;
	static public int idCount = 0;

	public void setup (float angle, float velocity, Vector2 pos)
	{
		var motion = Projectile.getComponents (angle, velocity);
		prevPos = pos;
		currPos = pos + motion;
		transform.position = currPos;
		id = ++idCount;
	}

	public void UpdatePoint ()
	{
		var accelerationMotion = acceleration * Time.fixedDeltaTime * Time.fixedDeltaTime;
		var previousMotion = currPos - prevPos;
		var Temp = currPos;
		currPos += previousMotion + accelerationMotion;
		prevPos = Temp;
		transform.position = currPos;
	}
	/// <summary>
	/// Moves to new position and saves the old one.
	/// </summary>
	/// <param name="newPos">New position.</param>
	public void moveTo (Vector2 newPos)
	{
		prevPos = currPos;
		currPos = newPos;
		transform.position = currPos;
	}
	/// <summary>
	/// Moves by delta and saves the old position.
	/// </summary>
	/// <param name="delta">Movement.</param>
	public void moveBy (Vector2 delta)
	{
		moveTo (currPos + delta);
	}
}

