//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class Block : MonoBehaviour
{
	public static int size = 1;
	public Vector2 coord;
	public Dictionary<Maze.Direction, GameObject> wallObjects = new Dictionary<Maze.Direction, GameObject>();
	public Dictionary<Maze.Direction, bool> wallBool = new Dictionary<Maze.Direction, bool> {
		{Maze.Direction.North, true},
		{Maze.Direction.East, true},
		{Maze.Direction.South, true},
		{Maze.Direction.West, true}
	};

	public int visited = 0;
	
	public Block ()
	{

	}
	//public Block(int X, int Y) {

		//Block ();
		//x = X;
		//y = Y;
	void Awake() {
		wallObjects[Maze.Direction.North] = transform.Find("wallN").gameObject;
		wallObjects[Maze.Direction.East ] = transform.Find("wallE").gameObject;
		wallObjects[Maze.Direction.South] = transform.Find("wallS").gameObject;
		wallObjects[Maze.Direction.West ] = transform.Find("wallW").gameObject;
	}
	void Start() {
		//transform.localScale = new Vector3(size,size,size);
//		walls = { {Maze.Direction.North, transform.Find ("wallN").gameObject},
//			{Maze.Direction.East, transform.Find ("wallE").gameObject},
//			{Maze.Direction.South, transform.Find ("wallS").gameObject},
//			{Maze.Direction.West, transform.Find ("wallW").gameObject} };

	}
	public void removeWall(Maze.Direction dir) {
		Destroy (wallObjects[dir]);
		wallBool[dir] = false;
	}
}

