//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;

namespace CustomExtensions
{
	public static class CustomExtensions
	{
		public static void Shuffle<T>(this IList<T> list)  
		{ 
			int n = list.Count;  
			while (n > 1) {
				n--;
				int k = UnityEngine.Random.Range(0, n + 1);  
				T value = list[k];  
				list[k] = list[n];  
				list[n] = value;  
			}  
		}
	}
}
